# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/rrivera/CorrelatorTrigger/TimingDistribution/TimingDistributionClient/ctp7-v7-base-fw/build/ctp7_top/ctp7_top_project.srcs/sources_1/bd/2017/ip/v7_bd_auto_pc_0/v7_bd_auto_pc_0.xci
# IP: The module: 'v7_bd_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/rrivera/CorrelatorTrigger/TimingDistribution/TimingDistributionClient/ctp7-v7-base-fw/build/ctp7_top/ctp7_top_project.srcs/sources_1/bd/2017/ip/v7_bd_auto_pc_0/v7_bd_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'v7_bd_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/rrivera/CorrelatorTrigger/TimingDistribution/TimingDistributionClient/ctp7-v7-base-fw/build/ctp7_top/ctp7_top_project.srcs/sources_1/bd/2017/ip/v7_bd_auto_pc_0/v7_bd_auto_pc_0.xci
# IP: The module: 'v7_bd_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/rrivera/CorrelatorTrigger/TimingDistribution/TimingDistributionClient/ctp7-v7-base-fw/build/ctp7_top/ctp7_top_project.srcs/sources_1/bd/2017/ip/v7_bd_auto_pc_0/v7_bd_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'v7_bd_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
