# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/rrivera/CorrelatorTrigger/TimingDistribution/TimingDistributionClient/ctp7-v7-base-fw/firmware/constraints/constraints.xdc

# IP: /home/rrivera/CorrelatorTrigger/TimingDistribution/GEM_AMC-3/ctp7/ip/sync_fifo_gth_40/sync_fifo_gth_40.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sync_fifo_gth_40 || ORIG_REF_NAME==sync_fifo_gth_40} -quiet] -quiet

# IP: /home/rrivera/CorrelatorTrigger/TimingDistribution/GEM_AMC-3/ctp7/ip/xlx_k7v7_rx_dpram/xlx_k7v7_rx_dpram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xlx_k7v7_rx_dpram || ORIG_REF_NAME==xlx_k7v7_rx_dpram} -quiet] -quiet

# IP: /home/rrivera/CorrelatorTrigger/TimingDistribution/GEM_AMC-3/ctp7/ip/xlx_k7v7_tx_dpram/xlx_k7v7_tx_dpram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xlx_k7v7_tx_dpram || ORIG_REF_NAME==xlx_k7v7_tx_dpram} -quiet] -quiet

# Block Designs: bd/2017/v7_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd || ORIG_REF_NAME==v7_bd} -quiet] -quiet

# IP: bd/2017/ip/v7_bd_axi_chip2chip_0_0/v7_bd_axi_chip2chip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_axi_chip2chip_0_0 || ORIG_REF_NAME==v7_bd_axi_chip2chip_0_0} -quiet] -quiet

# IP: bd/2017/ip/v7_bd_axi_interconnect_0_0/v7_bd_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_axi_interconnect_0_0 || ORIG_REF_NAME==v7_bd_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/2017/ip/v7_bd_clk_wiz_0_0/v7_bd_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_clk_wiz_0_0 || ORIG_REF_NAME==v7_bd_clk_wiz_0_0} -quiet] -quiet

# IP: bd/2017/ip/v7_bd_proc_sys_reset_0_0/v7_bd_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_proc_sys_reset_0_0 || ORIG_REF_NAME==v7_bd_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/2017/ip/v7_bd_xadc_wiz_0_0/v7_bd_xadc_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_xadc_wiz_0_0 || ORIG_REF_NAME==v7_bd_xadc_wiz_0_0} -quiet] -quiet

# IP: bd/2017/ip/v7_bd_xbar_0/v7_bd_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_xbar_0 || ORIG_REF_NAME==v7_bd_xbar_0} -quiet] -quiet

# IP: bd/2017/ip/v7_bd_auto_pc_0/v7_bd_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_auto_pc_0 || ORIG_REF_NAME==v7_bd_auto_pc_0} -quiet] -quiet

# XDC: bd/2017/v7_bd_ooc.xdc
